# Generated by Django 3.0.2 on 2020-02-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treehacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photouploader',
            name='name',
            field=models.CharField(default=' ', max_length=120),
        ),
    ]
